- hosts: all

  tasks:
    - name: Install scripts to /opt
      copy:
        src: ../../haproxy-dynamic-weight
        dest: /opt
    - name: install cron job to request dynamic weights
      cron:
        name: "haproxy-dynamic-weight-request"
        minute: "*/5"
        job: "python3 /opt/haproxy-dynamic-weight/set-lb-weight.py 127.0.0.1:11211"
        cron_file: "/etc/cron.d/set"
        user: root
